import type { Metadata } from "next";
import "./globals.css";
import { CssBaseline } from "@mui/material";
import StoreProvider from "@/src/app/StoreProvider";

export const metadata: Metadata = {
  title: "Gasification app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CssBaseline />
      <body>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
